### ISSUE TITLE
Adding sdk-jvm to android gradle

### ISSUE THREAD

**Issue by omartaha1003** [kuzzleio/sdk-jvm#34]
I'm trying to use kuzzle in my android application using sdk-jvm in gradle file, and the app will not build after adding it, you can check the log using this [Link](https://pastebin.com/MyJrUSbA)

## Steps to Reproduce
1- add the maven url in project gradle file in repositories as following:
maven {
            url  "http://dl.bintray.com/kuzzle/maven"
        }

2- add the sdk-jvm under dependencies in module app gradle file as following:
implementation 'io.kuzzle:sdk-jvm:1.0.1'

3- Sync dependecies and the rebuild the app

**Comment by ameenoz** [comment]
Hello @Yoann-Abbes , is this bug scheduled to be solved any time soon??

**Comment by Yoann-Abbes** [comment]
Hi @ameenoz 
We are currently resolving the problem by releasing a thin jar (without dependencies)
It will be released and documented very soon
You can visit the pull request here: https://github.com/kuzzleio/sdk-jvm/pull/45

**Comment by Yoann-Abbes** [comment]
Hi @omartaha1003 @ameenoz 

A thin jar without dependencies (a _thin jar_ ) has been released, which resolves the duplicates dependencies issue in a Android/Kotlin environment
We also documented a workaround if you still want to use the fat jar _(the fat jar)._

You can find the new 1.2.0 version with the jars here https://bintray.com/kuzzle/maven/sdk-jvm
And the updated Getting Started here https://docs.kuzzle.io/sdk/jvm/1/getting-started/kotlin/ 

If you use the fat jar you can still use `implementation 'io.kuzzle:sdk-jvm:1.2.0'`

Otherwise, if you want to use the thin jar use `implementation 'io.kuzzle:sdk-jvm:1.2.0-without-dependencies'` as described on Bintray 
If you use the thin jar, you will have to add others dependencies as described in the Getting Started
I close the issue

**Comment by omartaha1003** [comment]
Hello @Yoann-Abbes ,
I've been told that sdk-jvm would work on android api23(Java 7), but still this sdk is using classes from java 8 which makes the app crashes. The crash happens when I call the method kuzzle.connect(), which is using the class "CompletableFuture" inside "io.kuzzle.sdk.protocol.WebSocket".
When will we be able to use it on java 7 ?
